version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: saas_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: saas_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d saas_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: